//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.ServiceReference_Paciente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Paciente.PacienteSoap")]
    public interface PacienteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento condicion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostrarPaciente", ReplyAction="*")]
        SitioWeb.ServiceReference_Paciente.mostrarPacienteResponse mostrarPaciente(SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostrarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.mostrarPacienteResponse> mostrarPacienteAsync(SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarPaciente", ReplyAction="*")]
        SitioWeb.ServiceReference_Paciente.registrarPacienteResponse registrarPaciente(SitioWeb.ServiceReference_Paciente.registrarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.registrarPacienteResponse> registrarPacienteAsync(SitioWeb.ServiceReference_Paciente.registrarPacienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarUsuario", ReplyAction="*")]
        SitioWeb.ServiceReference_Paciente.validarUsuarioResponse validarUsuario(SitioWeb.ServiceReference_Paciente.validarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.validarUsuarioResponse> validarUsuarioAsync(SitioWeb.ServiceReference_Paciente.validarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminarPacienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPaciente", ReplyAction="*")]
        SitioWeb.ServiceReference_Paciente.eliminarPacienteResponse eliminarPaciente(SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.eliminarPacienteResponse> eliminarPacienteAsync(SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarPaciente", ReplyAction="*")]
        SitioWeb.ServiceReference_Paciente.modificarPacienteResponse modificarPaciente(SitioWeb.ServiceReference_Paciente.modificarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.modificarPacienteResponse> modificarPacienteAsync(SitioWeb.ServiceReference_Paciente.modificarPacienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mostrarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mostrarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.mostrarPacienteRequestBody Body;
        
        public mostrarPacienteRequest() {
        }
        
        public mostrarPacienteRequest(SitioWeb.ServiceReference_Paciente.mostrarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mostrarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string condicion;
        
        public mostrarPacienteRequestBody() {
        }
        
        public mostrarPacienteRequestBody(string condicion) {
            this.condicion = condicion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mostrarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mostrarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.mostrarPacienteResponseBody Body;
        
        public mostrarPacienteResponse() {
        }
        
        public mostrarPacienteResponse(SitioWeb.ServiceReference_Paciente.mostrarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mostrarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mostrarPacienteResult;
        
        public mostrarPacienteResponseBody() {
        }
        
        public mostrarPacienteResponseBody(string mostrarPacienteResult) {
            this.mostrarPacienteResult = mostrarPacienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.registrarPacienteRequestBody Body;
        
        public registrarPacienteRequest() {
        }
        
        public registrarPacienteRequest(SitioWeb.ServiceReference_Paciente.registrarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrasena;
        
        public registrarPacienteRequestBody() {
        }
        
        public registrarPacienteRequestBody(string nombre, string apellido, string email, string contrasena) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.registrarPacienteResponseBody Body;
        
        public registrarPacienteResponse() {
        }
        
        public registrarPacienteResponse(SitioWeb.ServiceReference_Paciente.registrarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarPacienteResult;
        
        public registrarPacienteResponseBody() {
        }
        
        public registrarPacienteResponseBody(string registrarPacienteResult) {
            this.registrarPacienteResult = registrarPacienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.validarUsuarioRequestBody Body;
        
        public validarUsuarioRequest() {
        }
        
        public validarUsuarioRequest(SitioWeb.ServiceReference_Paciente.validarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validarUsuarioRequestBody() {
        }
        
        public validarUsuarioRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.validarUsuarioResponseBody Body;
        
        public validarUsuarioResponse() {
        }
        
        public validarUsuarioResponse(SitioWeb.ServiceReference_Paciente.validarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validarUsuarioResult;
        
        public validarUsuarioResponseBody() {
        }
        
        public validarUsuarioResponseBody(string validarUsuarioResult) {
            this.validarUsuarioResult = validarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.eliminarPacienteRequestBody Body;
        
        public eliminarPacienteRequest() {
        }
        
        public eliminarPacienteRequest(SitioWeb.ServiceReference_Paciente.eliminarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int íd;
        
        public eliminarPacienteRequestBody() {
        }
        
        public eliminarPacienteRequestBody(int íd) {
            this.íd = íd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.eliminarPacienteResponseBody Body;
        
        public eliminarPacienteResponse() {
        }
        
        public eliminarPacienteResponse(SitioWeb.ServiceReference_Paciente.eliminarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminarPacienteResult;
        
        public eliminarPacienteResponseBody() {
        }
        
        public eliminarPacienteResponseBody(string eliminarPacienteResult) {
            this.eliminarPacienteResult = eliminarPacienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.modificarPacienteRequestBody Body;
        
        public modificarPacienteRequest() {
        }
        
        public modificarPacienteRequest(SitioWeb.ServiceReference_Paciente.modificarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        public modificarPacienteRequestBody() {
        }
        
        public modificarPacienteRequestBody(int id, string nombre, string apellido, string email, string contrasena) {
            this.id = id;
            this.nombre = nombre;
            this.apellido = apellido;
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Paciente.modificarPacienteResponseBody Body;
        
        public modificarPacienteResponse() {
        }
        
        public modificarPacienteResponse(SitioWeb.ServiceReference_Paciente.modificarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modificarPacienteResult;
        
        public modificarPacienteResponseBody() {
        }
        
        public modificarPacienteResponseBody(string modificarPacienteResult) {
            this.modificarPacienteResult = modificarPacienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PacienteSoapChannel : SitioWeb.ServiceReference_Paciente.PacienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacienteSoapClient : System.ServiceModel.ClientBase<SitioWeb.ServiceReference_Paciente.PacienteSoap>, SitioWeb.ServiceReference_Paciente.PacienteSoap {
        
        public PacienteSoapClient() {
        }
        
        public PacienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Paciente.mostrarPacienteResponse SitioWeb.ServiceReference_Paciente.PacienteSoap.mostrarPaciente(SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest request) {
            return base.Channel.mostrarPaciente(request);
        }
        
        public string mostrarPaciente(string condicion) {
            SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.mostrarPacienteRequestBody();
            inValue.Body.condicion = condicion;
            SitioWeb.ServiceReference_Paciente.mostrarPacienteResponse retVal = ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).mostrarPaciente(inValue);
            return retVal.Body.mostrarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.mostrarPacienteResponse> SitioWeb.ServiceReference_Paciente.PacienteSoap.mostrarPacienteAsync(SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest request) {
            return base.Channel.mostrarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.mostrarPacienteResponse> mostrarPacienteAsync(string condicion) {
            SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.mostrarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.mostrarPacienteRequestBody();
            inValue.Body.condicion = condicion;
            return ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).mostrarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Paciente.registrarPacienteResponse SitioWeb.ServiceReference_Paciente.PacienteSoap.registrarPaciente(SitioWeb.ServiceReference_Paciente.registrarPacienteRequest request) {
            return base.Channel.registrarPaciente(request);
        }
        
        public string registrarPaciente(string nombre, string apellido, string email, string contrasena) {
            SitioWeb.ServiceReference_Paciente.registrarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.registrarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.registrarPacienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            SitioWeb.ServiceReference_Paciente.registrarPacienteResponse retVal = ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).registrarPaciente(inValue);
            return retVal.Body.registrarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.registrarPacienteResponse> SitioWeb.ServiceReference_Paciente.PacienteSoap.registrarPacienteAsync(SitioWeb.ServiceReference_Paciente.registrarPacienteRequest request) {
            return base.Channel.registrarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.registrarPacienteResponse> registrarPacienteAsync(string nombre, string apellido, string email, string contrasena) {
            SitioWeb.ServiceReference_Paciente.registrarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.registrarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.registrarPacienteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            return ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).registrarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Paciente.validarUsuarioResponse SitioWeb.ServiceReference_Paciente.PacienteSoap.validarUsuario(SitioWeb.ServiceReference_Paciente.validarUsuarioRequest request) {
            return base.Channel.validarUsuario(request);
        }
        
        public string validarUsuario(string username, string password) {
            SitioWeb.ServiceReference_Paciente.validarUsuarioRequest inValue = new SitioWeb.ServiceReference_Paciente.validarUsuarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.validarUsuarioRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            SitioWeb.ServiceReference_Paciente.validarUsuarioResponse retVal = ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).validarUsuario(inValue);
            return retVal.Body.validarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.validarUsuarioResponse> SitioWeb.ServiceReference_Paciente.PacienteSoap.validarUsuarioAsync(SitioWeb.ServiceReference_Paciente.validarUsuarioRequest request) {
            return base.Channel.validarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.validarUsuarioResponse> validarUsuarioAsync(string username, string password) {
            SitioWeb.ServiceReference_Paciente.validarUsuarioRequest inValue = new SitioWeb.ServiceReference_Paciente.validarUsuarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.validarUsuarioRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).validarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Paciente.eliminarPacienteResponse SitioWeb.ServiceReference_Paciente.PacienteSoap.eliminarPaciente(SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest request) {
            return base.Channel.eliminarPaciente(request);
        }
        
        public string eliminarPaciente(int íd) {
            SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.eliminarPacienteRequestBody();
            inValue.Body.íd = íd;
            SitioWeb.ServiceReference_Paciente.eliminarPacienteResponse retVal = ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).eliminarPaciente(inValue);
            return retVal.Body.eliminarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.eliminarPacienteResponse> SitioWeb.ServiceReference_Paciente.PacienteSoap.eliminarPacienteAsync(SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest request) {
            return base.Channel.eliminarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.eliminarPacienteResponse> eliminarPacienteAsync(int íd) {
            SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.eliminarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.eliminarPacienteRequestBody();
            inValue.Body.íd = íd;
            return ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).eliminarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Paciente.modificarPacienteResponse SitioWeb.ServiceReference_Paciente.PacienteSoap.modificarPaciente(SitioWeb.ServiceReference_Paciente.modificarPacienteRequest request) {
            return base.Channel.modificarPaciente(request);
        }
        
        public string modificarPaciente(int id, string nombre, string apellido, string email, string contrasena) {
            SitioWeb.ServiceReference_Paciente.modificarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.modificarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.modificarPacienteRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            SitioWeb.ServiceReference_Paciente.modificarPacienteResponse retVal = ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).modificarPaciente(inValue);
            return retVal.Body.modificarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.modificarPacienteResponse> SitioWeb.ServiceReference_Paciente.PacienteSoap.modificarPacienteAsync(SitioWeb.ServiceReference_Paciente.modificarPacienteRequest request) {
            return base.Channel.modificarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Paciente.modificarPacienteResponse> modificarPacienteAsync(int id, string nombre, string apellido, string email, string contrasena) {
            SitioWeb.ServiceReference_Paciente.modificarPacienteRequest inValue = new SitioWeb.ServiceReference_Paciente.modificarPacienteRequest();
            inValue.Body = new SitioWeb.ServiceReference_Paciente.modificarPacienteRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            return ((SitioWeb.ServiceReference_Paciente.PacienteSoap)(this)).modificarPacienteAsync(inValue);
        }
    }
}
