//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.ServiceReference_Cita {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Cita.WebService_CitaSoap")]
    public interface WebService_CitaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechaSeleccionada del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCita", ReplyAction="*")]
        SitioWeb.ServiceReference_Cita.registrarCitaResponse registrarCita(SitioWeb.ServiceReference_Cita.registrarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.registrarCitaResponse> registrarCitaAsync(SitioWeb.ServiceReference_Cita.registrarCitaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarPacientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarPacientes", ReplyAction="*")]
        SitioWeb.ServiceReference_Cita.listarPacientesResponse listarPacientes(SitioWeb.ServiceReference_Cita.listarPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.listarPacientesResponse> listarPacientesAsync(SitioWeb.ServiceReference_Cita.listarPacientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarVeterinariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarVeterinarios", ReplyAction="*")]
        SitioWeb.ServiceReference_Cita.listarVeterinariosResponse listarVeterinarios(SitioWeb.ServiceReference_Cita.listarVeterinariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarVeterinarios", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.listarVeterinariosResponse> listarVeterinariosAsync(SitioWeb.ServiceReference_Cita.listarVeterinariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento condicion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCita", ReplyAction="*")]
        SitioWeb.ServiceReference_Cita.TraerCitaResponse TraerCita(SitioWeb.ServiceReference_Cita.TraerCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCita", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.TraerCitaResponse> TraerCitaAsync(SitioWeb.ServiceReference_Cita.TraerCitaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminarCitaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCita", ReplyAction="*")]
        SitioWeb.ServiceReference_Cita.eliminarCitaResponse eliminarCita(SitioWeb.ServiceReference_Cita.eliminarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.eliminarCitaResponse> eliminarCitaAsync(SitioWeb.ServiceReference_Cita.eliminarCitaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarCita", ReplyAction="*")]
        SitioWeb.ServiceReference_Cita.modificarCitaResponse modificarCita(SitioWeb.ServiceReference_Cita.modificarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.modificarCitaResponse> modificarCitaAsync(SitioWeb.ServiceReference_Cita.modificarCitaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCita", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.registrarCitaRequestBody Body;
        
        public registrarCitaRequest() {
        }
        
        public registrarCitaRequest(SitioWeb.ServiceReference_Cita.registrarCitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int paciente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaSeleccionada;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int medico;
        
        public registrarCitaRequestBody() {
        }
        
        public registrarCitaRequestBody(int paciente, string fechaSeleccionada, string hora, int medico) {
            this.paciente = paciente;
            this.fechaSeleccionada = fechaSeleccionada;
            this.hora = hora;
            this.medico = medico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.registrarCitaResponseBody Body;
        
        public registrarCitaResponse() {
        }
        
        public registrarCitaResponse(SitioWeb.ServiceReference_Cita.registrarCitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCitaResult;
        
        public registrarCitaResponseBody() {
        }
        
        public registrarCitaResponseBody(string registrarCitaResult) {
            this.registrarCitaResult = registrarCitaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarPacientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarPacientes", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.listarPacientesRequestBody Body;
        
        public listarPacientesRequest() {
        }
        
        public listarPacientesRequest(SitioWeb.ServiceReference_Cita.listarPacientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarPacientesRequestBody {
        
        public listarPacientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarPacientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.listarPacientesResponseBody Body;
        
        public listarPacientesResponse() {
        }
        
        public listarPacientesResponse(SitioWeb.ServiceReference_Cita.listarPacientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarPacientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listarPacientesResult;
        
        public listarPacientesResponseBody() {
        }
        
        public listarPacientesResponseBody(string listarPacientesResult) {
            this.listarPacientesResult = listarPacientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarVeterinariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarVeterinarios", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.listarVeterinariosRequestBody Body;
        
        public listarVeterinariosRequest() {
        }
        
        public listarVeterinariosRequest(SitioWeb.ServiceReference_Cita.listarVeterinariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarVeterinariosRequestBody {
        
        public listarVeterinariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarVeterinariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarVeterinariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.listarVeterinariosResponseBody Body;
        
        public listarVeterinariosResponse() {
        }
        
        public listarVeterinariosResponse(SitioWeb.ServiceReference_Cita.listarVeterinariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarVeterinariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listarVeterinariosResult;
        
        public listarVeterinariosResponseBody() {
        }
        
        public listarVeterinariosResponseBody(string listarVeterinariosResult) {
            this.listarVeterinariosResult = listarVeterinariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerCita", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.TraerCitaRequestBody Body;
        
        public TraerCitaRequest() {
        }
        
        public TraerCitaRequest(SitioWeb.ServiceReference_Cita.TraerCitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerCitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string condicion;
        
        public TraerCitaRequestBody() {
        }
        
        public TraerCitaRequestBody(string condicion) {
            this.condicion = condicion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerCitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.TraerCitaResponseBody Body;
        
        public TraerCitaResponse() {
        }
        
        public TraerCitaResponse(SitioWeb.ServiceReference_Cita.TraerCitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerCitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TraerCitaResult;
        
        public TraerCitaResponseBody() {
        }
        
        public TraerCitaResponseBody(string TraerCitaResult) {
            this.TraerCitaResult = TraerCitaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarCita", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.eliminarCitaRequestBody Body;
        
        public eliminarCitaRequest() {
        }
        
        public eliminarCitaRequest(SitioWeb.ServiceReference_Cita.eliminarCitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarCitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int íd;
        
        public eliminarCitaRequestBody() {
        }
        
        public eliminarCitaRequestBody(int íd) {
            this.íd = íd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarCitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.eliminarCitaResponseBody Body;
        
        public eliminarCitaResponse() {
        }
        
        public eliminarCitaResponse(SitioWeb.ServiceReference_Cita.eliminarCitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarCitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminarCitaResult;
        
        public eliminarCitaResponseBody() {
        }
        
        public eliminarCitaResponseBody(string eliminarCitaResult) {
            this.eliminarCitaResult = eliminarCitaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarCita", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.modificarCitaRequestBody Body;
        
        public modificarCitaRequest() {
        }
        
        public modificarCitaRequest(SitioWeb.ServiceReference_Cita.modificarCitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarCitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int paciente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int doctor;
        
        public modificarCitaRequestBody() {
        }
        
        public modificarCitaRequestBody(int id, int paciente, string fecha, string hora, int doctor) {
            this.id = id;
            this.paciente = paciente;
            this.fecha = fecha;
            this.hora = hora;
            this.doctor = doctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarCitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Cita.modificarCitaResponseBody Body;
        
        public modificarCitaResponse() {
        }
        
        public modificarCitaResponse(SitioWeb.ServiceReference_Cita.modificarCitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarCitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modificarCitaResult;
        
        public modificarCitaResponseBody() {
        }
        
        public modificarCitaResponseBody(string modificarCitaResult) {
            this.modificarCitaResult = modificarCitaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_CitaSoapChannel : SitioWeb.ServiceReference_Cita.WebService_CitaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_CitaSoapClient : System.ServiceModel.ClientBase<SitioWeb.ServiceReference_Cita.WebService_CitaSoap>, SitioWeb.ServiceReference_Cita.WebService_CitaSoap {
        
        public WebService_CitaSoapClient() {
        }
        
        public WebService_CitaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_CitaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CitaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CitaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Cita.registrarCitaResponse SitioWeb.ServiceReference_Cita.WebService_CitaSoap.registrarCita(SitioWeb.ServiceReference_Cita.registrarCitaRequest request) {
            return base.Channel.registrarCita(request);
        }
        
        public string registrarCita(int paciente, string fechaSeleccionada, string hora, int medico) {
            SitioWeb.ServiceReference_Cita.registrarCitaRequest inValue = new SitioWeb.ServiceReference_Cita.registrarCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.registrarCitaRequestBody();
            inValue.Body.paciente = paciente;
            inValue.Body.fechaSeleccionada = fechaSeleccionada;
            inValue.Body.hora = hora;
            inValue.Body.medico = medico;
            SitioWeb.ServiceReference_Cita.registrarCitaResponse retVal = ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).registrarCita(inValue);
            return retVal.Body.registrarCitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.registrarCitaResponse> SitioWeb.ServiceReference_Cita.WebService_CitaSoap.registrarCitaAsync(SitioWeb.ServiceReference_Cita.registrarCitaRequest request) {
            return base.Channel.registrarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.registrarCitaResponse> registrarCitaAsync(int paciente, string fechaSeleccionada, string hora, int medico) {
            SitioWeb.ServiceReference_Cita.registrarCitaRequest inValue = new SitioWeb.ServiceReference_Cita.registrarCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.registrarCitaRequestBody();
            inValue.Body.paciente = paciente;
            inValue.Body.fechaSeleccionada = fechaSeleccionada;
            inValue.Body.hora = hora;
            inValue.Body.medico = medico;
            return ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).registrarCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Cita.listarPacientesResponse SitioWeb.ServiceReference_Cita.WebService_CitaSoap.listarPacientes(SitioWeb.ServiceReference_Cita.listarPacientesRequest request) {
            return base.Channel.listarPacientes(request);
        }
        
        public string listarPacientes() {
            SitioWeb.ServiceReference_Cita.listarPacientesRequest inValue = new SitioWeb.ServiceReference_Cita.listarPacientesRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.listarPacientesRequestBody();
            SitioWeb.ServiceReference_Cita.listarPacientesResponse retVal = ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).listarPacientes(inValue);
            return retVal.Body.listarPacientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.listarPacientesResponse> SitioWeb.ServiceReference_Cita.WebService_CitaSoap.listarPacientesAsync(SitioWeb.ServiceReference_Cita.listarPacientesRequest request) {
            return base.Channel.listarPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.listarPacientesResponse> listarPacientesAsync() {
            SitioWeb.ServiceReference_Cita.listarPacientesRequest inValue = new SitioWeb.ServiceReference_Cita.listarPacientesRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.listarPacientesRequestBody();
            return ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).listarPacientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Cita.listarVeterinariosResponse SitioWeb.ServiceReference_Cita.WebService_CitaSoap.listarVeterinarios(SitioWeb.ServiceReference_Cita.listarVeterinariosRequest request) {
            return base.Channel.listarVeterinarios(request);
        }
        
        public string listarVeterinarios() {
            SitioWeb.ServiceReference_Cita.listarVeterinariosRequest inValue = new SitioWeb.ServiceReference_Cita.listarVeterinariosRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.listarVeterinariosRequestBody();
            SitioWeb.ServiceReference_Cita.listarVeterinariosResponse retVal = ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).listarVeterinarios(inValue);
            return retVal.Body.listarVeterinariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.listarVeterinariosResponse> SitioWeb.ServiceReference_Cita.WebService_CitaSoap.listarVeterinariosAsync(SitioWeb.ServiceReference_Cita.listarVeterinariosRequest request) {
            return base.Channel.listarVeterinariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.listarVeterinariosResponse> listarVeterinariosAsync() {
            SitioWeb.ServiceReference_Cita.listarVeterinariosRequest inValue = new SitioWeb.ServiceReference_Cita.listarVeterinariosRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.listarVeterinariosRequestBody();
            return ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).listarVeterinariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Cita.TraerCitaResponse SitioWeb.ServiceReference_Cita.WebService_CitaSoap.TraerCita(SitioWeb.ServiceReference_Cita.TraerCitaRequest request) {
            return base.Channel.TraerCita(request);
        }
        
        public string TraerCita(string condicion) {
            SitioWeb.ServiceReference_Cita.TraerCitaRequest inValue = new SitioWeb.ServiceReference_Cita.TraerCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.TraerCitaRequestBody();
            inValue.Body.condicion = condicion;
            SitioWeb.ServiceReference_Cita.TraerCitaResponse retVal = ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).TraerCita(inValue);
            return retVal.Body.TraerCitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.TraerCitaResponse> SitioWeb.ServiceReference_Cita.WebService_CitaSoap.TraerCitaAsync(SitioWeb.ServiceReference_Cita.TraerCitaRequest request) {
            return base.Channel.TraerCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.TraerCitaResponse> TraerCitaAsync(string condicion) {
            SitioWeb.ServiceReference_Cita.TraerCitaRequest inValue = new SitioWeb.ServiceReference_Cita.TraerCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.TraerCitaRequestBody();
            inValue.Body.condicion = condicion;
            return ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).TraerCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Cita.eliminarCitaResponse SitioWeb.ServiceReference_Cita.WebService_CitaSoap.eliminarCita(SitioWeb.ServiceReference_Cita.eliminarCitaRequest request) {
            return base.Channel.eliminarCita(request);
        }
        
        public string eliminarCita(int íd) {
            SitioWeb.ServiceReference_Cita.eliminarCitaRequest inValue = new SitioWeb.ServiceReference_Cita.eliminarCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.eliminarCitaRequestBody();
            inValue.Body.íd = íd;
            SitioWeb.ServiceReference_Cita.eliminarCitaResponse retVal = ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).eliminarCita(inValue);
            return retVal.Body.eliminarCitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.eliminarCitaResponse> SitioWeb.ServiceReference_Cita.WebService_CitaSoap.eliminarCitaAsync(SitioWeb.ServiceReference_Cita.eliminarCitaRequest request) {
            return base.Channel.eliminarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.eliminarCitaResponse> eliminarCitaAsync(int íd) {
            SitioWeb.ServiceReference_Cita.eliminarCitaRequest inValue = new SitioWeb.ServiceReference_Cita.eliminarCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.eliminarCitaRequestBody();
            inValue.Body.íd = íd;
            return ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).eliminarCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Cita.modificarCitaResponse SitioWeb.ServiceReference_Cita.WebService_CitaSoap.modificarCita(SitioWeb.ServiceReference_Cita.modificarCitaRequest request) {
            return base.Channel.modificarCita(request);
        }
        
        public string modificarCita(int id, int paciente, string fecha, string hora, int doctor) {
            SitioWeb.ServiceReference_Cita.modificarCitaRequest inValue = new SitioWeb.ServiceReference_Cita.modificarCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.modificarCitaRequestBody();
            inValue.Body.id = id;
            inValue.Body.paciente = paciente;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.doctor = doctor;
            SitioWeb.ServiceReference_Cita.modificarCitaResponse retVal = ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).modificarCita(inValue);
            return retVal.Body.modificarCitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.modificarCitaResponse> SitioWeb.ServiceReference_Cita.WebService_CitaSoap.modificarCitaAsync(SitioWeb.ServiceReference_Cita.modificarCitaRequest request) {
            return base.Channel.modificarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Cita.modificarCitaResponse> modificarCitaAsync(int id, int paciente, string fecha, string hora, int doctor) {
            SitioWeb.ServiceReference_Cita.modificarCitaRequest inValue = new SitioWeb.ServiceReference_Cita.modificarCitaRequest();
            inValue.Body = new SitioWeb.ServiceReference_Cita.modificarCitaRequestBody();
            inValue.Body.id = id;
            inValue.Body.paciente = paciente;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.doctor = doctor;
            return ((SitioWeb.ServiceReference_Cita.WebService_CitaSoap)(this)).modificarCitaAsync(inValue);
        }
    }
}
