//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.ServiceReference_Vet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Vet.DoctorSoap")]
    public interface DoctorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento condicion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostrarVeterinario", ReplyAction="*")]
        SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponse mostrarVeterinario(SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mostrarVeterinario", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponse> mostrarVeterinarioAsync(SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarVeterinario", ReplyAction="*")]
        SitioWeb.ServiceReference_Vet.registrarVeterinarioResponse registrarVeterinario(SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarVeterinario", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.registrarVeterinarioResponse> registrarVeterinarioAsync(SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminarVeterinarioResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarVeterinario", ReplyAction="*")]
        SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponse eliminarVeterinario(SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarVeterinario", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponse> eliminarVeterinarioAsync(SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarVeterinario", ReplyAction="*")]
        SitioWeb.ServiceReference_Vet.modificarVeterinarioResponse modificarVeterinario(SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarVeterinario", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.modificarVeterinarioResponse> modificarVeterinarioAsync(SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mostrarVeterinarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mostrarVeterinario", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequestBody Body;
        
        public mostrarVeterinarioRequest() {
        }
        
        public mostrarVeterinarioRequest(SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mostrarVeterinarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string condicion;
        
        public mostrarVeterinarioRequestBody() {
        }
        
        public mostrarVeterinarioRequestBody(string condicion) {
            this.condicion = condicion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mostrarVeterinarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mostrarVeterinarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponseBody Body;
        
        public mostrarVeterinarioResponse() {
        }
        
        public mostrarVeterinarioResponse(SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mostrarVeterinarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mostrarVeterinarioResult;
        
        public mostrarVeterinarioResponseBody() {
        }
        
        public mostrarVeterinarioResponseBody(string mostrarVeterinarioResult) {
            this.mostrarVeterinarioResult = mostrarVeterinarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarVeterinarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarVeterinario", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.registrarVeterinarioRequestBody Body;
        
        public registrarVeterinarioRequest() {
        }
        
        public registrarVeterinarioRequest(SitioWeb.ServiceReference_Vet.registrarVeterinarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarVeterinarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        public registrarVeterinarioRequestBody() {
        }
        
        public registrarVeterinarioRequestBody(string nombre, string apellido) {
            this.nombre = nombre;
            this.apellido = apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarVeterinarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarVeterinarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.registrarVeterinarioResponseBody Body;
        
        public registrarVeterinarioResponse() {
        }
        
        public registrarVeterinarioResponse(SitioWeb.ServiceReference_Vet.registrarVeterinarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarVeterinarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarVeterinarioResult;
        
        public registrarVeterinarioResponseBody() {
        }
        
        public registrarVeterinarioResponseBody(string registrarVeterinarioResult) {
            this.registrarVeterinarioResult = registrarVeterinarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarVeterinarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarVeterinario", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequestBody Body;
        
        public eliminarVeterinarioRequest() {
        }
        
        public eliminarVeterinarioRequest(SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarVeterinarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int íd;
        
        public eliminarVeterinarioRequestBody() {
        }
        
        public eliminarVeterinarioRequestBody(int íd) {
            this.íd = íd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarVeterinarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarVeterinarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponseBody Body;
        
        public eliminarVeterinarioResponse() {
        }
        
        public eliminarVeterinarioResponse(SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarVeterinarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminarVeterinarioResult;
        
        public eliminarVeterinarioResponseBody() {
        }
        
        public eliminarVeterinarioResponseBody(string eliminarVeterinarioResult) {
            this.eliminarVeterinarioResult = eliminarVeterinarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarVeterinarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarVeterinario", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.modificarVeterinarioRequestBody Body;
        
        public modificarVeterinarioRequest() {
        }
        
        public modificarVeterinarioRequest(SitioWeb.ServiceReference_Vet.modificarVeterinarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarVeterinarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        public modificarVeterinarioRequestBody() {
        }
        
        public modificarVeterinarioRequestBody(int id, string nombre, string apellido) {
            this.id = id;
            this.nombre = nombre;
            this.apellido = apellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarVeterinarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarVeterinarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.ServiceReference_Vet.modificarVeterinarioResponseBody Body;
        
        public modificarVeterinarioResponse() {
        }
        
        public modificarVeterinarioResponse(SitioWeb.ServiceReference_Vet.modificarVeterinarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarVeterinarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modificarVeterinarioResult;
        
        public modificarVeterinarioResponseBody() {
        }
        
        public modificarVeterinarioResponseBody(string modificarVeterinarioResult) {
            this.modificarVeterinarioResult = modificarVeterinarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoctorSoapChannel : SitioWeb.ServiceReference_Vet.DoctorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoctorSoapClient : System.ServiceModel.ClientBase<SitioWeb.ServiceReference_Vet.DoctorSoap>, SitioWeb.ServiceReference_Vet.DoctorSoap {
        
        public DoctorSoapClient() {
        }
        
        public DoctorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoctorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponse SitioWeb.ServiceReference_Vet.DoctorSoap.mostrarVeterinario(SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest request) {
            return base.Channel.mostrarVeterinario(request);
        }
        
        public string mostrarVeterinario(string condicion) {
            SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequestBody();
            inValue.Body.condicion = condicion;
            SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponse retVal = ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).mostrarVeterinario(inValue);
            return retVal.Body.mostrarVeterinarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponse> SitioWeb.ServiceReference_Vet.DoctorSoap.mostrarVeterinarioAsync(SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest request) {
            return base.Channel.mostrarVeterinarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.mostrarVeterinarioResponse> mostrarVeterinarioAsync(string condicion) {
            SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.mostrarVeterinarioRequestBody();
            inValue.Body.condicion = condicion;
            return ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).mostrarVeterinarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Vet.registrarVeterinarioResponse SitioWeb.ServiceReference_Vet.DoctorSoap.registrarVeterinario(SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest request) {
            return base.Channel.registrarVeterinario(request);
        }
        
        public string registrarVeterinario(string nombre, string apellido) {
            SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.registrarVeterinarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            SitioWeb.ServiceReference_Vet.registrarVeterinarioResponse retVal = ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).registrarVeterinario(inValue);
            return retVal.Body.registrarVeterinarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.registrarVeterinarioResponse> SitioWeb.ServiceReference_Vet.DoctorSoap.registrarVeterinarioAsync(SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest request) {
            return base.Channel.registrarVeterinarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.registrarVeterinarioResponse> registrarVeterinarioAsync(string nombre, string apellido) {
            SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.registrarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.registrarVeterinarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            return ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).registrarVeterinarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponse SitioWeb.ServiceReference_Vet.DoctorSoap.eliminarVeterinario(SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest request) {
            return base.Channel.eliminarVeterinario(request);
        }
        
        public string eliminarVeterinario(int íd) {
            SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequestBody();
            inValue.Body.íd = íd;
            SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponse retVal = ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).eliminarVeterinario(inValue);
            return retVal.Body.eliminarVeterinarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponse> SitioWeb.ServiceReference_Vet.DoctorSoap.eliminarVeterinarioAsync(SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest request) {
            return base.Channel.eliminarVeterinarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.eliminarVeterinarioResponse> eliminarVeterinarioAsync(int íd) {
            SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.eliminarVeterinarioRequestBody();
            inValue.Body.íd = íd;
            return ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).eliminarVeterinarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.ServiceReference_Vet.modificarVeterinarioResponse SitioWeb.ServiceReference_Vet.DoctorSoap.modificarVeterinario(SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest request) {
            return base.Channel.modificarVeterinario(request);
        }
        
        public string modificarVeterinario(int id, string nombre, string apellido) {
            SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.modificarVeterinarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            SitioWeb.ServiceReference_Vet.modificarVeterinarioResponse retVal = ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).modificarVeterinario(inValue);
            return retVal.Body.modificarVeterinarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.modificarVeterinarioResponse> SitioWeb.ServiceReference_Vet.DoctorSoap.modificarVeterinarioAsync(SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest request) {
            return base.Channel.modificarVeterinarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.ServiceReference_Vet.modificarVeterinarioResponse> modificarVeterinarioAsync(int id, string nombre, string apellido) {
            SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest inValue = new SitioWeb.ServiceReference_Vet.modificarVeterinarioRequest();
            inValue.Body = new SitioWeb.ServiceReference_Vet.modificarVeterinarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            return ((SitioWeb.ServiceReference_Vet.DoctorSoap)(this)).modificarVeterinarioAsync(inValue);
        }
    }
}
